version: "3.9"

services:
  backend:
    build: ./backend
    container_name: jobtracker-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: jobtracker-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"

volumes:
  postgres_data:
